[project]
name = "wfm"
version = "0.1.0"
description = ""
authors = [
    {name = "Davide Riva",email = "60431521+dave-shore@users.noreply.github.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
]

[tool.poetry]
packages = [{include = "wfm", from = "src"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
